trigger:
  - master

pool:
  vmImage: 'window-latest'

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - script: echo Hello, world!

  - stage: deploy_dev
    displayName: Deploy to development
    variables:
    - group: dev
    jobs:
      - deployment: deploy
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, development world!
                - task: replacetokens@3
                  inputs:
                    targetFiles: '$(Pipeline.Workspace)/dist/**/main*.js'
                    encoding: 'auto'
                    writeBOM: true
                    verbosity: 'detailed'
                    actionOnMissing: 'warn'
                    keepToken: false
                    tokenPrefix: '#{'
                    tokenSuffix: '}#'
                    useLegacyPattern: false
                    enableTelemetry: true

  - stage: deploy_prod
    displayName: Deploy to production
    variables:
      - group: prod
    jobs:
    - deployment: deploy
      environment: PROD
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, production world!
              - task: replacetokens@3
                inputs:
                  targetFiles: '$(Pipeline.Workspace)/dist/**/main*.js'
                  encoding: 'auto'
                  writeBOM: true
                  verbosity: 'detailed'
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
                  useLegacyPattern: false
                  enableTelemetry: true